/* ### Create a schema (model) for users ### */

const mongoose = require("mongoose"); /* import "mongoose" package - allows use to create a strict schema with the requires fields and their type */
const uniqueValidator = require("mongoose-unique-validator"); /*import "mongoose unique validator" package - allows to be certain some elements are unique  (e.g. user email) */

const userSchema = mongoose.Schema({ /* id fields are automatically generated by mongoose so do not need to be included in the schema */
    email: {type: String, required: true, unique: true},
    password: {type: String, required: true}
});

userSchema.plugin(uniqueValidator);

module.exports = mongoose.model("User", userSchema); /* exports the users model */